name: 'Generate main webpage from Handlebars template'

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: GenerateWebsite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Handlebars Action
        uses: pedrolamas/handlebars-action@v2.1.0
        with:
          # Files to process
          files: index.hbs
          # Output filename template
          output-filename: {{ file.dir }}/index.html
      - name: Commit
        uses: actions/checkout@v3
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Regenerate index.html"
          git push
