name: 'Generate main webpage from Handlebars template'

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: GenerateWebsite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Handlebars Install
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm install -g handlebars-cmd
      - name: Handlebars Render
        run: |
          handlebars data.json < index.hbs > index.html
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "feat: Regenerate index.html"
          git push
