name: 'Generate main webpage from Handlebars template'

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: GenerateWebsite
    runs-on: ubuntu-latest
    steps:
      - name: GetCurrentDate
        id: date
        run: echo "::set-output name=date::"
        run: echo "{date}={$(date +"%d/%m/%Y a las %H:%M")}" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
      - name: Handlebars Render
        uses: mikeal/npx@master
        with:
          args: 'hbs-cli --data data.json --data "{\"currentDate\": \"$CURRENT_DATE\"}" index.hbs -output index.html'
        env:
          CURRENT_DATE: ${{ steps.date.outputs.date }}
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "feat: Regenerate index.html"
          git push
